/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElLoading: typeof import('element-plus/es')['ElLoading']
  const ElRow: typeof import('element-plus/es')['ElRow']
}
